## Importing libraries

In [1]:
import pandas as pd
films = pd.read_csv('movies_clean.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'movies_clean.csv'

In [125]:
films[['genres', 'production_countries']]

,genres,production_countries
0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...","[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'is..."
1,"[{'id': 35, 'name': 'Comedy'}, {'id': 27, 'nam...","[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso..."
2,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso..."
3,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...","[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso..."
4,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'..."
...,...,...
9773,"[{'id': 9648, 'name': 'Mystery'}, {'id': 18, '...","[{'iso_3166_1': 'CA', 'name': 'Canada'}]"
9774,"[{'id': 28, 'name': 'Action'}, {'id': 9648, 'n...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso..."
9775,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...","[{'iso_3166_1': 'CA', 'name': 'Canada'}]"
9776,"[{'id': 35, 'name': 'Comedy'}]","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso..."
9777,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso..."

## Null Values

In [126]:
films.isnull().sum()

genres                  0
id                      0
original_language       0
original_title          0
overview                0
popularity              0
poster_path             0
production_companies    0
production_countries    0
release_date            0
runtime                 0
spoken_languages        0
title                   0
vote_average            0
vote_count              0
cast                    0
crew                    0
year                    0
director                0
director_gender         0
dtype: int64

In [127]:
films.isna().sum()

genres                  0
id                      0
original_language       0
original_title          0
overview                0
popularity              0
poster_path             0
production_companies    0
production_countries    0
release_date            0
runtime                 0
spoken_languages        0
title                   0
vote_average            0
vote_count              0
cast                    0
crew                    0
year                    0
director                0
director_gender         0
dtype: int64

## Drop Duplicates

In [128]:
films.drop_duplicates(subset='id', inplace=True)
films['id'].value_counts()

11860     1
167956    1
68744     1
44023     1
84508     1
         ..
43389     1
14298     1
9381      1
16182     1
30840     1
Name: id, Length: 9769, dtype: int64

## Investigating outliers

In [129]:
films['vote_average'].sort_values()

6057     0.0
3785     0.0
8053     0.0
9301     0.0
3081     0.0
        ...
8434    10.0
5357    10.0
4987    10.0
3960    10.0
7827    10.0
Name: vote_average, Length: 9769, dtype: float64

In [130]:
# I decided to drop this column, as well as "vote_count" because I saw that "Call Me by Your Name", a very popular film, had a vote average 0. I will keep the column "popularity" which is more reliable, with a value of 4.300874.
films[films['vote_average'] == 0.0]
films.drop(columns=['vote_average','vote_count'], inplace=True)

In [131]:
#I checked the relevance of "popularity" column by checking the movies with lowest and highest rates.
films['popularity'].sort_values()
films['popularity'].sort_values(ascending=False)
films.loc[9462]

genres                  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
id                                                                 339403
original_language                                                 English
original_title                                                Baby Driver
overview                After being coerced into working for a crime b...
popularity                                                     228.032744
poster_path                              /dN9LbVNNZFITwfaRjl4tmwGWkRg.jpg
production_companies    [{'name': 'Big Talk Productions', 'id': 443}, ...
production_countries    [{'iso_3166_1': 'GB', 'name': 'United Kingdom'...
release_date                                                   2017-06-28
runtime                                                             113.0
spoken_languages                                                        1
title                                                         Baby Driver
cast                    [{'cast_id': 9, 'character': 'Baby', 'credit_i...
crew                    [{'credit_id': '55c58c009251417a21000e5d', 'de...
year                                                                 2017
director                                                     Edgar Wright
director_gender                                                      male
Name: 9462, dtype: object

In [132]:
films.groupby('id')['popularity'].sum().sort_values(ascending=False)[:10]

id
321612    287.253654
339403    228.032744
315837     68.726676
550        63.869599
406990     60.581223
440597     59.578823
403119     52.854103
360249     50.949523
353491     50.903593
258489     45.382980
Name: popularity, dtype: float64

In [133]:
films = films.drop(films[films['popularity'] == 287.253654].index)
films = films.drop(films[films['popularity'] == 228.032744].index)

## Fixing columns

In [134]:
# I decided to remove spaces from genre names because it would later be a problem when vectorizing (ie: ScienceFiction)

def fix_genres_names(x):
    x = str(x)
    genres = []
    
    if 'Comedy' in x:
        genres.append('Comedy')
    if 'Action' in x:
        genres.append('Action')
    if 'Drama' in x:
        genres.append('Drama')
    if 'Crime' in x:
        genres.append('Crime')
    if 'Romance' in x:
        genres.append('Romance')
    if 'Adventure' in x:
        genres.append('Adventure')
    if 'Thriller' in x:
        genres.append('Thriller')
    if 'Fantasy' in x:
        genres.append('Fantasy')
    if 'Science Fiction' in x:
        genres.append('ScienceFiction')
    if 'History' in x:
        genres.append('History')
    if 'War' in x:
        genres.append('War')
    if 'Foreign' in x:
        genres.append('Foreign')
    if 'Mystery' in x:
        genres.append('Mystery')
    if 'Family' in x:
        genres.append('Family')
    if 'Documentary' in x:
        genres.append('Documentary')
    if 'Horror' in x:
        genres.append('Horror')
    if 'Animation' in x:
        genres.append('Animation')
    if 'Western' in x:
        genres.append('Western')
    if 'Music' in x:
        genres.append('Music')
    if 'TV Movie' in x:
        genres.append('TVMovie')
    
    if genres:
        return ', '.join(genres)
    else:
        return 'nAn'

In [135]:
films['genres'] = films['genres'].apply(fix_genres_names)

In [136]:
#188 null values
films[films['genres'] ==  'nAn']

,genres,id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,runtime,spoken_languages,title,cast,crew,year,director,director_gender
171,nAn,172198,Hungarian,Bűvös vadász,"A battle-scarred, has-been Hungarian cop, torm...",0.091984,/3phxETl3dV31eAbcML1pBt5x0EC.jpg,"[{'name': 'Új Budapest Filmstudió', 'id': 1655...","[{'iso_3166_1': 'HU', 'name': 'Hungary'}, {'is...",1994-10-23,106.0,1,Magic Hunter,"[{'cast_id': 4, 'character': 'Max', 'credit_id...","[{'credit_id': '52fe4d1bc3a36847f824efa5', 'de...",1994,Ildikó Enyedi,female
182,nAn,42758,English,Small Faces,"Three teenage brothers, gang-member Bobby, tro...",0.909130,/s9I3gLu9ySsfyM3JvlpSW9KrszF.jpg,[],"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",1996-04-05,108.0,1,Small Faces,"[{'cast_id': 1, 'character': 'Lex Maclean', 'c...","[{'credit_id': '52fe4617c3a36847f80ec48d', 'de...",1996,Gillies MacKinnon,male
412,nAn,52907,English,Waltzes from Vienna,The story of Johann Strauss the elder and youn...,0.751957,/jnXsVjBSfcgRxFOmxZpbwCe2Mrg.jpg,[{'name': 'Gaumont British Picture Corporation...,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",1934-01-31,81.0,1,Waltzes from Vienna,"[{'cast_id': 2, 'character': 'Johann Strauss, ...","[{'credit_id': '52fe4849c3a36847f815fbc1', 'de...",1934,Alfred Hitchcock,male
566,nAn,42020,Spanish,El amor brujo,"In a Gypsy village, the fathers of Candela and...",0.185772,/8EA9bmQgeH6KUlsneql6GHydqYy.jpg,[],"[{'iso_3166_1': 'ES', 'name': 'Spain'}]",1986-03-23,100.0,1,El Amor Brujo,"[{'cast_id': 4, 'character': 'Carmelo', 'credi...","[{'credit_id': '52fe45e9c3a36847f80e1a05', 'de...",1986,Carlos Saura,male
652,nAn,67455,French,La nuit fantastique,"Denis, a poor student in philosophy, works as ...",0.543794,/bL2z18OIGyBOJacM2ZT37Xz52BK.jpg,[],"[{'iso_3166_1': 'FR', 'name': 'France'}]",1942-07-10,103.0,1,The Fantastic Night,"[{'cast_id': 2, 'character': 'Denis', 'credit_...","[{'credit_id': '52fe4767c3a368484e0c5137', 'de...",1942,Marcel L'Herbier,male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9621,nAn,254479,Chinese,Fish and Elephant,The story follows the elephant keeper in the B...,0.436679,/mMNXeeEfqbJBVVWydKbWp2pgw16.jpg,[],"[{'iso_3166_1': 'CN', 'name': 'China'}]",2001-09-01,106.0,1,Fish and Elephant,[],"[{'credit_id': '530368de92514121a45c5fff', 'de...",2001,Li Yu,female
9661,nAn,56304,Russian,Сатисфакция,"Главный герой Александр, крупный бизнесмен и в...",0.468259,/sxsglmofLcRIZxacMmKiV8IoTBn.jpg,[],"[{'iso_3166_1': 'RU', 'name': 'Russia'}]",2011-01-20,93.0,1,Satisfaktsiya,"[{'cast_id': 1002, 'character': 'Dima', 'credi...","[{'credit_id': '52fe48f8c3a36847f8182b37', 'de...",2011,Anna Matison,female
9677,nAn,143068,Russian,Станционный смотритель,In the early 19th century a traveler returns t...,0.002001,/dJrO98IJsOe18E0LcVhioprSfDQ.jpg,"[{'name': 'Mosfilm', 'id': 5120}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1972-08-25,68.0,1,The Postmaster,"[{'cast_id': 4, 'character': '', 'credit_id': ...","[{'credit_id': '52fe4afb9251416c750f4617', 'de...",1972,Sergey Solovyov,male
9730,nAn,63320,English,Lions Love,"“The pressures here in Hollywood are so great,...",0.112507,/s8r1oFBHcRymIDhwWKa4ysbiET7.jpg,[],"[{'iso_3166_1': 'US', 'name': 'United States o...",1969-09-20,110.0,1,Lions Love,"[{'cast_id': 6, 'character': 'Viva', 'credit_i...","[{'credit_id': '52fe46a5c3a368484e09c077', 'de...",1969,Agnès Varda,female
9763,nAn,408624,English,A Death in the Gunj,A sensitive university student unraveling whil...,0.516993,/ksqGltfJzYJL3lV4YvoIkVgcU55.jpg,"[{'name': 'Studioz IDrream', 'id': 85800}, {'n...","[{'iso_3166_1': 'IN', 'name': 'India'}]",2016-09-10,110.0,2,A Death in the Gunj,"[{'cast_id': 1, 'character': 'Shyamlal Chatter...","[{'credit_id': '58877d529251415ff70053e7', 'de...",2016,Konkona Sen Sharma,female

In [137]:
#Drop the null values in 'Genres'
films = films.drop(films[films['genres'] == 'nAn'].index)

In [138]:
films[films['genres'] ==  'nAn']

Empty DataFrame
Columns: [genres, id, original_language, original_title, overview, popularity, poster_path, production_companies, production_countries, release_date, runtime, spoken_languages, title, cast, crew, year, director, director_gender]
Index: []

In [139]:
#Fix production countries
films['prod_countries'] = films['production_countries'].str.extract(r"'name': '([^']*)'")
films['prod_countries'].unique()

array(['Germany', 'France', 'United Kingdom', 'Italy', 'China',
       'United States of America', 'Canada', 'Belgium', 'Iran',
       'Hong Kong', 'Dominican Republic', 'Ireland', 'Taiwan',
       'New Zealand', 'Mexico', 'Japan', 'Peru', 'Australia',
       'South Africa', 'Denmark', 'Finland', 'Spain', 'South Korea',
       'Sweden', 'Argentina', 'Austria', 'Czech Republic', 'Vietnam',
       'Switzerland', 'Trinidad and Tobago', 'Portugal', 'Russia',
       'India', 'Brazil', 'Norway', 'Aruba', 'Israel', 'Luxembourg',
       'Poland', 'Cuba', 'Malaysia', 'Bulgaria', 'Serbia', 'Greece',
       'Thailand', 'Cameroon', 'Colombia', 'Netherlands', 'Philippines',
       'Libyan Arab Jamahiriya', 'Iceland', 'Soviet Union', 'Turkey',
       'Singapore', 'Bosnia and Herzegovina', 'Czechoslovakia',
       'Martinique', 'Romania', 'Armenia', 'Egypt', 'Indonesia',
       'Hungary', 'Chile', 'Monaco', 'Uruguay', 'Algeria', 'Lithuania',
       'Palestinian Territory', 'East Germany', 'Morocco', 'Lebanon',
       'Latvia', 'United Arab Emirates', 'Slovenia', 'Cambodia',
       'Botswana', 'Pakistan', 'Congo', 'Tanzania', 'Bolivia',
       'Kazakhstan', 'Ethiopia', 'Qatar', 'Tajikistan', 'Belarus',
       'Estonia', 'Georgia', 'Mauritania', 'Burkina Faso', 'Afghanistan',
       'Croatia', 'Yugoslavia', 'Malta', 'Nicaragua', 'Ukraine',
       'Venezuela', 'Iraq', 'Liechtenstein', 'Albania', 'Macedonia'],
      dtype=object)

In [140]:
    def fix_countries(x):
        x = str(x)
        genres = []
    
        if 'Germany' in x:
            genres.append('Germany')
        if 'France' in x:
            genres.append('France')
        if 'United Kingdom' in x:
            genres.append('United Kingdom')
        if 'Italy' in x:
            genres.append('Italy')
        if 'China' in x:
            genres.append('China')
        if 'United States of America' in x:
            genres.append('United States of America')
        if 'Canada' in x:
            genres.append('Canada')
        if 'Belgium' in x:
            genres.append('Belgium')
        if 'Iran' in x:
            genres.append('Iran')
        if 'Hong Kong' in x:
            genres.append('Hong Kong')
        if 'Dominican Republic' in x:
            genres.append('Dominican Republic')
        if 'Ireland' in x:
            genres.append('Ireland')
        if 'Taiwan' in x:
            genres.append('Taiwan')
        if 'New Zealand' in x:
            genres.append('New Zealand')
        if 'Mexico' in x:
            genres.append('Mexico')
        if 'Japan' in x:
            genres.append('Japan')
        if 'Peru' in x:
            genres.append('Peru')
        if 'Australia' in x:
            genres.append('Australia')
        if 'South Africa' in x:
            genres.append('South Africa')
        if 'Denmark' in x:
            genres.append('Denmark')
        if 'Finland' in x:
            genres.append('Finland')
        if 'Spain' in x:
            genres.append('Spain')
        if 'Sweden' in x:
            genres.append('Sweden')
        if 'South Korea' in x:
            genres.append('South Korea')
        if 'Sweden' in x:
            genres.append('Sweden')
        if 'Argentina' in x:
            genres.append('Argentina')
        if 'Hungary' in x:
            genres.append('Hungary')
        if 'Austria' in x:
            genres.append('Austria')
        if 'Czech Republic' in x:
            genres.append('Czech Republic')
        if 'Vietnam' in x:
            genres.append('Vietnam')
        if 'Switzerland' in x:
            genres.append('Switzerland')
        if 'Trinidad and Tobago' in x:
            genres.append('Trinidad and Tobago')
        if 'Portugal' in x:
            genres.append('Portugal')
        if 'Russia' in x:
            genres.append('Russia')
        if 'India' in x:
            genres.append('India')
        if 'Brazil' in x:
            genres.append('Brazil')
        if 'Norway' in x:
            genres.append('Norway')
        if 'Aruba' in x:
            genres.append('Aruba')
        if 'Israel' in x:
            genres.append('Israel')
        if 'Luxembourg' in x:
            genres.append('Luxembourg')
        if 'Poland' in x:
            genres.append('Poland')
        if 'Cuba' in x:
            genres.append('Cuba')
        if 'Malaysia' in x:
            genres.append('Malaysia')
        if 'Bulgaria' in x:
            genres.append('Bulgaria')
        if 'Serbia' in x:
            genres.append('Serbia')
        if 'Greece' in x:
            genres.append('Greecee')
        if 'Thailand' in x:
            genres.append('Thailand')
        if 'Cameroon' in x:
            genres.append('Cameroon')
        if 'Colombia' in x:
            genres.append('Colombia')
        if 'Netherlands' in x:
            genres.append('Netherlands')
        if 'Philippines' in x:
            genres.append('Philippines')
        if 'Libyan Arab Jamahiriya' in x:
            genres.append('Libyan Arab Jamahiriya')
        if 'Iceland' in x:
            genres.append('Iceland')
        if 'Soviet Union' in x:
            genres.append('Soviet Union')
        if 'Turkey' in x:
            genres.append('Turkey')
        if 'Singapore' in x:
            genres.append('Singapore')
        if 'Bosnia and Herzegovina' in x:
            genres.append('Bosnia and Herzegovina')
        if 'Czechoslovakia' in x:
            genres.append('Czechoslovakia')
        if 'Martinique' in x:
            genres.append('Martinique')
        if 'Romania' in x:
            genres.append('Romania')
        if 'Armenia' in x:
            genres.append('Armenia')
        if 'Egypt' in x:
            genres.append('Egypt')
        if 'Indonesia' in x:
            genres.append('Indonesia')
        if 'Chile' in x:
            genres.append('Chile')
        if 'Monaco' in x:
            genres.append('Monaco')
        if 'Uruguay' in x:
            genres.append('Uruguay')
        if 'Algeria' in x:
            genres.append('Algeria')
        if 'Lithuania' in x:
            genres.append('Lithuania')
        if 'Palestinian Territory' in x:
            genres.append('Palestinian Territory')
        if 'East Germany' in x:
            genres.append('East Germany')
        if 'Morocco' in x:
            genres.append('Morocco')
        if 'Lebanon' in x:
            genres.append('Lebanon')
        if 'Latvia' in x:
            genres.append('Latvia')
        if 'United Arab Emirates' in x:
            genres.append('United Arab Emirates')
        if 'Slovenia' in x:
            genres.append('Slovenia')
        if 'Cambodia' in x:
            genres.append('Cambodia')
        if 'Botswana' in x:
            genres.append('Botswana')
        if 'Pakistan' in x:
            genres.append('Pakistan')
        if 'Congo' in x:
            genres.append('Congo')
        if 'Tanzania' in x:
            genres.append('Tanzania')
        if 'Bolivia' in x:
            genres.append('Bolivia')
        if 'Kazakhstan' in x:
            genres.append('Kazakhstan')
        if 'Ethiopia' in x:
            genres.append('Ethiopia')
        if 'Qatar' in x:
            genres.append('Qatar')
        if 'Tajikistan' in x:
            genres.append('Tajikistan')
        if 'Belarus' in x:
            genres.append('Belarus')
        if 'Estonia' in x:
            genres.append('Estonia')
        if 'Georgia' in x:
            genres.append('Georgia')
        if 'Mauritania' in x:
            genres.append('Mauritania')
        if 'Burkina Faso' in x:
            genres.append('Burkina Faso')
        if 'Afghanistan' in x:
            genres.append('Afghanistan')
        if 'Croatia' in x:
            genres.append('Croatia')
        if 'Yugoslavia' in x:
            genres.append('Yugoslavia')
        if 'Malta' in x:
            genres.append('Malta')
        if 'Nicaragua' in x:
            genres.append('Nicaragua')
        if 'Ukraine' in x:
            genres.append('Ukraine')
        if 'Venezuela' in x:
            genres.append('Venezuela')
        if 'Iraq' in x:
            genres.append('Iraq')
        if 'Liechtenstein' in x:
            genres.append('Liechtenstein')
        if 'Albania' in x:
            genres.append('Albania')
        if 'Macedonia' in x:
            genres.append('Macedonia')
        if genres:
            return ', '.join(genres)
        else:
            return 'Unknown'

In [141]:
films['production_countries'] = films['production_countries'].apply(fix_countries)

In [142]:
#No null values
films[films['production_countries'] == 'Unkown']

Empty DataFrame
Columns: [genres, id, original_language, original_title, overview, popularity, poster_path, production_companies, production_countries, release_date, runtime, spoken_languages, title, cast, crew, year, director, director_gender, prod_countries]
Index: []

## Dropping columns

In [143]:
films.drop(columns=[ 'release_date', 'poster_path', 'cast', 'crew', 'prod_countries'], inplace=True)

## Exporting to CSV

In [144]:
films.to_csv('films_clean.csv', index=False)